package com.graphicalab.api

enum class ApiMethods {

    LOGIN, REGISTER, ADD_ORGANISATION, ADD_LOCATION, LOCATION_LIST, ADD_ROOM, ROOM_LIST, MEAL_LIST,
    ADD_HOTEL, HOTEL_LIST, ADD_TRANSPORT, TRANSPORT_LIST
}